<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskMaster.Pro.Application\TaskMaster.Pro.Application.csproj" />
    <ProjectReference Include="..\TaskMaster.Pro.Domain\TaskMaster.Pro.Domain.csproj" />
    <ProjectReference Include="..\TaskMaster.Pro.Shared\TaskMaster.Pro.Shared.csproj" />
  </ItemGroup>

</Project>
